### ISSUE TITLE
How to use this repository for parallel inference

### ISSUE THREAD

**Issue by LinyeLi60** [Billccx/multiviewPose#1]
你好，请问这个仓库支持并行推理嘛，具体如何使用呢？

**Comment by Billccx** [comment]
mediapipe本身具有多线程特性，请参考
https://google.github.io/mediapipe/getting_started/faq.html#how-to-run-calculators-in-parallel

**Comment by LinyeLi60** [comment]
感谢，请问你的代码只在cpu上测试过吗，有没有测试过gpu推理





------------------ Original ------------------
From: Billccx ***@***.***&gt;
Date: Fri,Jul 15,2022 0:26 PM
To: Billccx/multiviewPose ***@***.***&gt;
Cc: Linye Li ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Billccx/multiviewPose] How to use this repository for parallelinference (Issue #1)





 
mediapipe本身具有多线程特性，请参考
 https://google.github.io/mediapipe/getting_started/faq.html#how-to-run-calculators-in-parallel

**Comment by Billccx** [comment]
我目前只用过CPU推理

**Comment by LinyeLi60** [comment]
那么在cpu上速度提升如何呢





------------------ Original ------------------
From: Billccx ***@***.***&gt;
Date: Fri,Jul 15,2022 0:28 PM
To: Billccx/multiviewPose ***@***.***&gt;
Cc: Linye Li ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Billccx/multiviewPose] How to use this repository for parallel inference (Issue #1)





 
我目前只用过CPU推理

**Comment by Billccx** [comment]
你问的是那个模块的速度？是我写的内容还是mediapipe本身的模块？

**Comment by LinyeLi60** [comment]
就是相对于原来串行推理模型来比，现在改成并行推理了之后速度的提升





------------------ Original ------------------
From: Billccx ***@***.***&gt;
Date: Fri,Jul 15,2022 0:33 PM
To: Billccx/multiviewPose ***@***.***&gt;
Cc: Linye Li ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Billccx/multiviewPose] How to use this repository for parallel inference (Issue #1)





 
你问的是那个模块的速度？是我写的内容还是mediapipe本身的模块？

**Comment by Billccx** [comment]
通常情况下，如果不进行人为设定，按照计算图编译出来就已经自动并行优化了，我并没有试过单线程的情况。

**Comment by LinyeLi60** [comment]
好的，明白了，感谢解答





------------------ Original ------------------
From: Billccx ***@***.***&gt;
Date: Fri,Jul 15,2022 0:39 PM
To: Billccx/multiviewPose ***@***.***&gt;
Cc: Linye Li ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Billccx/multiviewPose] How to use this repository for parallelinference (Issue #1)





 
通常情况下，如果不进行人为设定，按照计算图编译出来就已经自动并行优化了，我并没有试过单线程的情况。
